name: Build LaTeX document

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_latex:
    name: Compile LaTeX document for Assignment ${{ matrix.assignmentNumber }}
    runs-on: ubuntu-18.04
    
    strategy:
        fail-fast: false
        matrix:
            assignmentNumber: [1]

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document 
        uses: xu-cheng/latex-action@v2
        with:
          root_file: Assignment${{ matrix.assignmentNumber }}/main.tex
