name: Build LaTeX document

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_latex:
    name: Compile LaTeX document for assignment ${{ matrix.assignment_no }}
    runs-on: ubuntu-18.04

    strategy:
        matrix:
            assignment_no: [1, 2, 3]
    
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Compile LaTeX document 
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: Assignment${{ matrix.assignment_no }}
